### ISSUE TITLE
new sm

### ISSUE THREAD

**Issue by trov4** [KSU-IEEE/statemachine#1]
@ntrinite create the new branch `1-new-sm` and be sure to post any updates here

**Comment by trov4** [comment]
Goal for first meeting:  
Have the nodelet interface written 
Stretch goal: 
determine method for have the ros-agnostic statemachine

**Comment by trov4** [comment]
Trevor's TODO for Noah: 
- Send him info on threading in nodelets
- Develop base nodelet

**Comment by trov4** [comment]
Added a base statemachine interface, runs a single control loop thread for now.

**Comment by trov4** [comment]
![PXL_20210123_203832619](https://user-images.githubusercontent.com/57910937/106077271-3e0dd700-60df-11eb-9d30-ce42603ff3a8.jpg)
![PXL_20210123_210614632](https://user-images.githubusercontent.com/57910937/106077273-3ea66d80-60df-11eb-864e-cf42973b887d.jpg)
![PXL_20210123_211822519](https://user-images.githubusercontent.com/57910937/106077275-3fd79a80-60df-11eb-91c3-5c1322f99be4.jpg)
![PXL_20210123_212528586](https://user-images.githubusercontent.com/57910937/106077277-40703100-60df-11eb-83ca-56475483c1d9.jpg)

@ntrinite

**Comment by ntrinite** [comment]
I DID SOMETHING

**Comment by ntrinite** [comment]
Every state works until the last reach_search
Transitions to attack_ghosts but attack_ghost doesn't take control

UPDATE
> -in attack_ghost.cpp at line 10 you had "attach_ghost not attack_ghost
> -After changing it, transitioning to attack_ghost got angry (see photo 1)

UPDATE 2
> -added return true to grab method in attack_ghost to see if that was something
> -added cout to parent_control_loop in base_beh and the control loop of attack_ghost. Every state printed out "...returning 0" (see photo 2) but attack_ghost printed out "...returning 1" (See photo 3)

UPDATE 3
> -Changed the return true to return false in the grab method but I don't think that really did anything
> -sometimes get something like photo 4 and 5?
> -seems to sometimes automatically transition to return_to_start state 
> -the amount of "...giving up control" messages vary in length (photo 6)

There are no photos because they were exchanged through discord. Just wanted to post on here to feel official

**Comment by ntrinite** [comment]
My life is the issue now because THIS STATE MACHINE BE DONE
